// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Tantrum4132/task-service/internal/repository (interfaces: StatsRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Tantrum4132/task-service/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockStatsRepository is a mock of StatsRepository interface.
type MockStatsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStatsRepositoryMockRecorder
}

// MockStatsRepositoryMockRecorder is the mock recorder for MockStatsRepository.
type MockStatsRepositoryMockRecorder struct {
	mock *MockStatsRepository
}

// NewMockStatsRepository creates a new mock instance.
func NewMockStatsRepository(ctrl *gomock.Controller) *MockStatsRepository {
	mock := &MockStatsRepository{ctrl: ctrl}
	mock.recorder = &MockStatsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsRepository) EXPECT() *MockStatsRepositoryMockRecorder {
	return m.recorder
}

// GetTeamStats mocks base method.
func (m *MockStatsRepository) GetTeamStats(arg0 context.Context, arg1 int64) (*model.TeamStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamStats", arg0, arg1)
	ret0, _ := ret[0].(*model.TeamStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamStats indicates an expected call of GetTeamStats.
func (mr *MockStatsRepositoryMockRecorder) GetTeamStats(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamStats", reflect.TypeOf((*MockStatsRepository)(nil).GetTeamStats), arg0, arg1)
}
