// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Tantrum4132/task-service/internal/service (interfaces: TaskCacheInvalidator)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTaskCacheInvalidator is a mock of TaskCacheInvalidator interface.
type MockTaskCacheInvalidator struct {
	ctrl     *gomock.Controller
	recorder *MockTaskCacheInvalidatorMockRecorder
}

// MockTaskCacheInvalidatorMockRecorder is the mock recorder for MockTaskCacheInvalidator.
type MockTaskCacheInvalidatorMockRecorder struct {
	mock *MockTaskCacheInvalidator
}

// NewMockTaskCacheInvalidator creates a new mock instance.
func NewMockTaskCacheInvalidator(ctrl *gomock.Controller) *MockTaskCacheInvalidator {
	mock := &MockTaskCacheInvalidator{ctrl: ctrl}
	mock.recorder = &MockTaskCacheInvalidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskCacheInvalidator) EXPECT() *MockTaskCacheInvalidatorMockRecorder {
	return m.recorder
}

// InvalidateTeamCache mocks base method.
func (m *MockTaskCacheInvalidator) InvalidateTeamCache(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateTeamCache", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateTeamCache indicates an expected call of InvalidateTeamCache.
func (mr *MockTaskCacheInvalidatorMockRecorder) InvalidateTeamCache(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateTeamCache", reflect.TypeOf((*MockTaskCacheInvalidator)(nil).InvalidateTeamCache), arg0, arg1)
}
