// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Tantrum4132/task-service/internal/service (interfaces: TaskService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/Tantrum4132/task-service/internal/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockTaskService is a mock of TaskService interface.
type MockTaskService struct {
	ctrl     *gomock.Controller
	recorder *MockTaskServiceMockRecorder
}

// MockTaskServiceMockRecorder is the mock recorder for MockTaskService.
type MockTaskServiceMockRecorder struct {
	mock *MockTaskService
}

// NewMockTaskService creates a new mock instance.
func NewMockTaskService(ctrl *gomock.Controller) *MockTaskService {
	mock := &MockTaskService{ctrl: ctrl}
	mock.recorder = &MockTaskServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskService) EXPECT() *MockTaskServiceMockRecorder {
	return m.recorder
}

// CreateComment mocks base method.
func (m *MockTaskService) CreateComment(arg0 context.Context, arg1, arg2 int64, arg3 dto.CreateCommentRequest) (*dto.TaskCommentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*dto.TaskCommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockTaskServiceMockRecorder) CreateComment(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockTaskService)(nil).CreateComment), arg0, arg1, arg2, arg3)
}

// CreateTask mocks base method.
func (m *MockTaskService) CreateTask(arg0 context.Context, arg1 int64, arg2 dto.CreateTaskRequest) (*dto.TaskResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", arg0, arg1, arg2)
	ret0, _ := ret[0].(*dto.TaskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTaskServiceMockRecorder) CreateTask(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTaskService)(nil).CreateTask), arg0, arg1, arg2)
}

// GetTaskByID mocks base method.
func (m *MockTaskService) GetTaskByID(arg0 context.Context, arg1, arg2 int64) (*dto.TaskResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*dto.TaskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByID indicates an expected call of GetTaskByID.
func (mr *MockTaskServiceMockRecorder) GetTaskByID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByID", reflect.TypeOf((*MockTaskService)(nil).GetTaskByID), arg0, arg1, arg2)
}

// GetTaskHistory mocks base method.
func (m *MockTaskService) GetTaskHistory(arg0 context.Context, arg1, arg2 int64, arg3, arg4 int) ([]dto.TaskHistoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskHistory", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]dto.TaskHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskHistory indicates an expected call of GetTaskHistory.
func (mr *MockTaskServiceMockRecorder) GetTaskHistory(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskHistory", reflect.TypeOf((*MockTaskService)(nil).GetTaskHistory), arg0, arg1, arg2, arg3, arg4)
}

// ListComments mocks base method.
func (m *MockTaskService) ListComments(arg0 context.Context, arg1, arg2 int64) ([]dto.TaskCommentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListComments", arg0, arg1, arg2)
	ret0, _ := ret[0].([]dto.TaskCommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListComments indicates an expected call of ListComments.
func (mr *MockTaskServiceMockRecorder) ListComments(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListComments", reflect.TypeOf((*MockTaskService)(nil).ListComments), arg0, arg1, arg2)
}

// ListTasks mocks base method.
func (m *MockTaskService) ListTasks(arg0 context.Context, arg1 int64, arg2 dto.TaskFilterQuery) ([]dto.TaskResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTasks", arg0, arg1, arg2)
	ret0, _ := ret[0].([]dto.TaskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTasks indicates an expected call of ListTasks.
func (mr *MockTaskServiceMockRecorder) ListTasks(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTasks", reflect.TypeOf((*MockTaskService)(nil).ListTasks), arg0, arg1, arg2)
}

// UpdateTask mocks base method.
func (m *MockTaskService) UpdateTask(arg0 context.Context, arg1, arg2 int64, arg3 dto.UpdateTaskRequest) (*dto.TaskResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*dto.TaskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockTaskServiceMockRecorder) UpdateTask(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockTaskService)(nil).UpdateTask), arg0, arg1, arg2, arg3)
}
