// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Tantrum4132/task-service/internal/repository (interfaces: TaskCommentRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Tantrum4132/task-service/internal/model"
	repository "github.com/Tantrum4132/task-service/internal/repository"
	gomock "github.com/golang/mock/gomock"
)

// MockTaskCommentRepository is a mock of TaskCommentRepository interface.
type MockTaskCommentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskCommentRepositoryMockRecorder
}

// MockTaskCommentRepositoryMockRecorder is the mock recorder for MockTaskCommentRepository.
type MockTaskCommentRepositoryMockRecorder struct {
	mock *MockTaskCommentRepository
}

// NewMockTaskCommentRepository creates a new mock instance.
func NewMockTaskCommentRepository(ctrl *gomock.Controller) *MockTaskCommentRepository {
	mock := &MockTaskCommentRepository{ctrl: ctrl}
	mock.recorder = &MockTaskCommentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskCommentRepository) EXPECT() *MockTaskCommentRepositoryMockRecorder {
	return m.recorder
}

// CreateComment mocks base method.
func (m *MockTaskCommentRepository) CreateComment(arg0 context.Context, arg1 repository.DBEngine, arg2 *model.TaskComment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComment", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateComment indicates an expected call of CreateComment.
func (mr *MockTaskCommentRepositoryMockRecorder) CreateComment(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComment", reflect.TypeOf((*MockTaskCommentRepository)(nil).CreateComment), arg0, arg1, arg2)
}

// DeleteComment mocks base method.
func (m *MockTaskCommentRepository) DeleteComment(arg0 context.Context, arg1 repository.DBEngine, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteComment", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteComment indicates an expected call of DeleteComment.
func (mr *MockTaskCommentRepositoryMockRecorder) DeleteComment(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteComment", reflect.TypeOf((*MockTaskCommentRepository)(nil).DeleteComment), arg0, arg1, arg2)
}

// GetCommentByID mocks base method.
func (m *MockTaskCommentRepository) GetCommentByID(arg0 context.Context, arg1 repository.DBEngine, arg2 int64) (*model.TaskComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentByID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.TaskComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentByID indicates an expected call of GetCommentByID.
func (mr *MockTaskCommentRepositoryMockRecorder) GetCommentByID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentByID", reflect.TypeOf((*MockTaskCommentRepository)(nil).GetCommentByID), arg0, arg1, arg2)
}

// ListCommentsByTaskID mocks base method.
func (m *MockTaskCommentRepository) ListCommentsByTaskID(arg0 context.Context, arg1 repository.DBEngine, arg2 int64) ([]model.TaskComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCommentsByTaskID", arg0, arg1, arg2)
	ret0, _ := ret[0].([]model.TaskComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCommentsByTaskID indicates an expected call of ListCommentsByTaskID.
func (mr *MockTaskCommentRepositoryMockRecorder) ListCommentsByTaskID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCommentsByTaskID", reflect.TypeOf((*MockTaskCommentRepository)(nil).ListCommentsByTaskID), arg0, arg1, arg2)
}
