// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Tantrum4132/task-service/internal/repository (interfaces: TaskHistoryRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Tantrum4132/task-service/internal/model"
	repository "github.com/Tantrum4132/task-service/internal/repository"
	gomock "github.com/golang/mock/gomock"
)

// MockTaskHistoryRepository is a mock of TaskHistoryRepository interface.
type MockTaskHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskHistoryRepositoryMockRecorder
}

// MockTaskHistoryRepositoryMockRecorder is the mock recorder for MockTaskHistoryRepository.
type MockTaskHistoryRepositoryMockRecorder struct {
	mock *MockTaskHistoryRepository
}

// NewMockTaskHistoryRepository creates a new mock instance.
func NewMockTaskHistoryRepository(ctrl *gomock.Controller) *MockTaskHistoryRepository {
	mock := &MockTaskHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockTaskHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskHistoryRepository) EXPECT() *MockTaskHistoryRepositoryMockRecorder {
	return m.recorder
}

// CreateTaskHistory mocks base method.
func (m *MockTaskHistoryRepository) CreateTaskHistory(arg0 context.Context, arg1 repository.DBEngine, arg2 *model.TaskHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTaskHistory", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTaskHistory indicates an expected call of CreateTaskHistory.
func (mr *MockTaskHistoryRepositoryMockRecorder) CreateTaskHistory(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTaskHistory", reflect.TypeOf((*MockTaskHistoryRepository)(nil).CreateTaskHistory), arg0, arg1, arg2)
}

// GetHistoryByTaskID mocks base method.
func (m *MockTaskHistoryRepository) GetHistoryByTaskID(arg0 context.Context, arg1 repository.DBEngine, arg2 repository.TaskHistoryFilter) ([]model.TaskHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistoryByTaskID", arg0, arg1, arg2)
	ret0, _ := ret[0].([]model.TaskHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistoryByTaskID indicates an expected call of GetHistoryByTaskID.
func (mr *MockTaskHistoryRepositoryMockRecorder) GetHistoryByTaskID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistoryByTaskID", reflect.TypeOf((*MockTaskHistoryRepository)(nil).GetHistoryByTaskID), arg0, arg1, arg2)
}
