// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Tantrum4132/task-service/internal/repository (interfaces: TeamMemberRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Tantrum4132/task-service/internal/model"
	repository "github.com/Tantrum4132/task-service/internal/repository"
	gomock "github.com/golang/mock/gomock"
)

// MockTeamMemberRepository is a mock of TeamMemberRepository interface.
type MockTeamMemberRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeamMemberRepositoryMockRecorder
}

// MockTeamMemberRepositoryMockRecorder is the mock recorder for MockTeamMemberRepository.
type MockTeamMemberRepositoryMockRecorder struct {
	mock *MockTeamMemberRepository
}

// NewMockTeamMemberRepository creates a new mock instance.
func NewMockTeamMemberRepository(ctrl *gomock.Controller) *MockTeamMemberRepository {
	mock := &MockTeamMemberRepository{ctrl: ctrl}
	mock.recorder = &MockTeamMemberRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamMemberRepository) EXPECT() *MockTeamMemberRepositoryMockRecorder {
	return m.recorder
}

// AddMember mocks base method.
func (m *MockTeamMemberRepository) AddMember(arg0 context.Context, arg1 repository.DBEngine, arg2 *model.TeamMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMember", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMember indicates an expected call of AddMember.
func (mr *MockTeamMemberRepositoryMockRecorder) AddMember(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMember", reflect.TypeOf((*MockTeamMemberRepository)(nil).AddMember), arg0, arg1, arg2)
}

// GetMember mocks base method.
func (m *MockTeamMemberRepository) GetMember(arg0 context.Context, arg1 repository.DBEngine, arg2, arg3 int64) (*model.TeamMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMember", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*model.TeamMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMember indicates an expected call of GetMember.
func (mr *MockTeamMemberRepositoryMockRecorder) GetMember(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMember", reflect.TypeOf((*MockTeamMemberRepository)(nil).GetMember), arg0, arg1, arg2, arg3)
}

// GetMemberRole mocks base method.
func (m *MockTeamMemberRepository) GetMemberRole(arg0 context.Context, arg1 repository.DBEngine, arg2, arg3 int64) (model.TeamRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemberRole", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(model.TeamRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMemberRole indicates an expected call of GetMemberRole.
func (mr *MockTeamMemberRepositoryMockRecorder) GetMemberRole(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemberRole", reflect.TypeOf((*MockTeamMemberRepository)(nil).GetMemberRole), arg0, arg1, arg2, arg3)
}

// IsMember mocks base method.
func (m *MockTeamMemberRepository) IsMember(arg0 context.Context, arg1 repository.DBEngine, arg2, arg3 int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMember", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMember indicates an expected call of IsMember.
func (mr *MockTeamMemberRepositoryMockRecorder) IsMember(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMember", reflect.TypeOf((*MockTeamMemberRepository)(nil).IsMember), arg0, arg1, arg2, arg3)
}

// ListTeamMembers mocks base method.
func (m *MockTeamMemberRepository) ListTeamMembers(arg0 context.Context, arg1 repository.DBEngine, arg2 int64) ([]model.TeamMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTeamMembers", arg0, arg1, arg2)
	ret0, _ := ret[0].([]model.TeamMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTeamMembers indicates an expected call of ListTeamMembers.
func (mr *MockTeamMemberRepositoryMockRecorder) ListTeamMembers(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTeamMembers", reflect.TypeOf((*MockTeamMemberRepository)(nil).ListTeamMembers), arg0, arg1, arg2)
}

// RemoveMember mocks base method.
func (m *MockTeamMemberRepository) RemoveMember(arg0 context.Context, arg1 repository.DBEngine, arg2, arg3 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMember", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMember indicates an expected call of RemoveMember.
func (mr *MockTeamMemberRepositoryMockRecorder) RemoveMember(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMember", reflect.TypeOf((*MockTeamMemberRepository)(nil).RemoveMember), arg0, arg1, arg2, arg3)
}

// UpdateMemberRole mocks base method.
func (m *MockTeamMemberRepository) UpdateMemberRole(arg0 context.Context, arg1 repository.DBEngine, arg2, arg3 int64, arg4 model.TeamRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMemberRole", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMemberRole indicates an expected call of UpdateMemberRole.
func (mr *MockTeamMemberRepositoryMockRecorder) UpdateMemberRole(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMemberRole", reflect.TypeOf((*MockTeamMemberRepository)(nil).UpdateMemberRole), arg0, arg1, arg2, arg3, arg4)
}
